name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: |
        sbt -Dplay.version=2.8.1 +test
        sbt -Dplay.version=2.7.4 +test
        sbt -Dplay.version=2.6.25 +test
